services:
  frontend:
    build: 
      context:  ./frontend
    container_name: 'frontend-shiftingpact'
    ports:
      - '4040:4040'
    depends_on:
      - backend
    networks:
      - backend-network
  
  backend:
    build: 
      context: ./backend
    container_name: 'backend-shiftingpact'
    ports:
      - '8080:8080'
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra  # Référence directe au service Cassandra via son nom
      - CASSANDRA_PORT=9042
    networks:
      - backend-network

  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_USER=${DB_USER}     
      - CASSANDRA_PASSWORD=${DB_PASSWORD}
    volumes:
      - cassandra-db:/var/lib/cassandra
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  cassandra-db: