services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    volumes:
      - cassandra-db:/var/lib/cassandra
      - ./initdb:/docker-entrypoint-initdb.d
      - ./cassandra-entrypoint.sh:/usr/local/bin/cassandra-entrypoint.sh
      - ./cqlshrc:/root/.cqlshrc
    entrypoint: ["/usr/local/bin/cassandra-entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", 'cqlsh -e "DESCRIBE KEYSPACE app;"']
      interval: 30s
      timeout: 60s
      retries: 10
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
    container_name: "frontend-shiftingpact"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
    container_name: "backend-shiftingpact"
    ports:
      - "8000:8000"
    depends_on:
      cassandra:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  cassandra-db:
